### ISSUE TITLE
Can not place multiple orders with JSON object param.

### ISSUE THREAD

**Issue by vuongnq10** [binance/binance-futures-connector-node#11]
### Issue subject
Source code comes from here 
https://github.com/binance/binance-futures-connector-node/blob/main/examples/um_futures/account/placeMultipleOrders.js
```javascript
const batchOrders = [
  { symbol: 'BNBUSDT', ...others},
  { symbol: 'BNBUSDT', ...others }
]
umFuturesClient
  .placeMultipleOrders(batchOrders)
  .then((response) => console.log(response))
  .catch(console.error)
```

### Expected behaviour

I believe that the request params should be transformed to string before sending

```javascript
const batchOrders = [
  { symbol: 'BNBUSDT', ...others},
  { symbol: 'BNBUSDT', ...others }
]
umFuturesClient
  .placeMultipleOrders(JSON.stringify(batchOrders))
  .then((response) => console.log(response))
  .catch(console.error)
```
I'm running my trading bot with this config and it works well
### Actual behaviour

N/A

### Steps to reproduce

N/A

### Environment

N/A

**Comment by alplabin** [comment]
Thanks for pointing out this issue. It has been updated in [v0.1.6](https://github.com/binance/binance-futures-connector-node/releases/tag/v0.1.6)
