### ISSUE TITLE
code":-1022,"msg":"Signature for this request is not valid." when connecting to TestNet

### ISSUE THREAD

**Issue by caronniwaston** [binance/binance-futures-connector-node#15]
### Issue subject

code":-1022,"msg":"Signature for this request is not valid." when connecting to TestNet

### Expected behaviour

Suppose this is the official Java API, and the samples should work using the API key and secret got from testnet - https://testnet.binancefuture.com/en/futures/BTCUSD

### Actual behaviour

The program I ran is src/test/java/examples/um_futures/account/NewOrder.java, the error is examples.cm_futures.account.NewOrder - fullErrMessage: {"code":-1022,"msg":"Signature for this request is not valid."}. Please help check why this official API failed.

### Steps to reproduce

* using the API key and secret got from testnet - https://testnet.binancefuture.com/en/futures/BTCUSD
* The program I ran is src/test/java/examples/um_futures/account/NewOrder.java
* Error returns - examples.cm_futures.account.NewOrder - fullErrMessage: {"code":-1022,"msg":"Signature for this request is not valid."}.

### Environment

Release [Release v0.1.5](https://github.com/binance/binance-futures-connector-node/commit/8788c59796fe6d660eace5fc24b8c9de6fd6617f)

MacOS + VSCode

**Comment by alplabin** [comment]
Hey,
If you are experiencing an issue with the Java futures connector, please consider opening a GitHub issue in the relevant repository.

Additionally, it looks like your request references a symbol (BTCUSD) that doesn’t exist on UM Futures. To see a list of all available symbols, use this endpoint: [GET /fapi/v1/exchangeInfo](https://developers.binance.com/docs/derivatives/usds-margined-futures/market-data/rest-api/Exchange-Information) - [Node Example File](https://github.com/binance/binance-futures-connector-node/blob/main/examples/um_futures/market/getExchangeInfo.js)

Lastly, your issue might be related to your API keys. Please refer to this article to troubleshoot: https://dev.binance.vision/t/faq-signature-for-this-request-is-not-valid/176
