### ISSUE TITLE
Refactor `Object.assign` Usage to Avoid Mutating the `options` Object

### ISSUE THREAD

**Issue by Mohamednowfil** [binance/binance-futures-connector-node#16]
### Issue:
The current implementation using Object.assign can lead to alterations in the original options object, which might create unexpected side effects in the application. This complicates code maintenance and debugging, while also making the behavior of the code harder to anticipate

**Fix**:
```js
// Before:
Object.assign(options, { symbol: symbol.toUpperCase(), side: side.toUpperCase() });

// ToFix:
const requestParams = { ...options, symbol: symbol.toUpperCase(), side: side.toUpperCase() };

**Comment by alplabin** [comment]
Hey,
Could you provide an example of the changes generated when using `Object.assign`?

**Comment by Mohamednowfil** [comment]
Hi , thank you for reviewing the issue, Sure I will explain for you

**Current code:**
```js
Object.assign(options, {
  symbol: symbol.toUpperCase(),
  side: side.toUpperCase(),
  type: type.toUpperCase(),
}); 

//Issue(it get mutated if options object is reused somewhere):

const options = { timeout: 5000 };
market.newOrder('BTC', 'BUY', 'LIMIT', options);
console.log(options);
// Output: { timeout: 5000, symbol: 'BTC', side: 'BUY', type: 'LIMIT' } // Mutated!
```
**Fix**:
spread operator to avoid mutating `options`
```js
const requestParams = { ...options, symbol: symbol.toUpperCase(), side: side.toUpperCase(), type: type.toUpperCase() };
```
**After Fix:**
```js
const options = { timeout: 5000 };
market.newOrder('BTC', 'BUY', 'LIMIT', options);
console.log(options);
// Output: { timeout: 5000 } // Unchanged
```
I think i clarified you clearly with example

**Comment by alplabin** [comment]
Thank for the clarification. It has been updated in [v0.1.6](https://github.com/binance/binance-futures-connector-node/releases/tag/v0.1.6)

**Comment by Mohamednowfil** [comment]
Thanks for the update, I tested the changes in v0.1.6, and that work as expected
