### ISSUE TITLE
Add Type Validation for `listenKey` Parameter in User Data Stream Methods

### ISSUE THREAD

**Issue by Mohamednowfil** [binance/binance-futures-connector-node#17]
### Issue Description:
The `listenKey` parameter, used in the `renewListenKey` and `closeListenKey` methods, is not validated for its type before being used in API requests. This can lead to potential runtime errors if `listenKey` is not a valid string, causing failures or unexpected behavior when interacting with the API.

### Problem:
The `listenKey` is being passed directly into API requests without validating if it's a string. This may cause issues if the `listenKey` is not properly validated, especially if a non-string value is provided.

### Suggested Fix:
Add a type validation for `listenKey` to ensure that it is always a string before being used in API requests.

**Example Fix**:
```js
// Before:
validateRequiredParameters({ listenKey });

// ToFix:
if (typeof listenKey !== 'string') {
  throw new Error('ListenKey must be a string');
}
validateRequiredParameters({ listenKey });

**Comment by Mohamednowfil** [comment]
I not created in ai and other suggestion see in Object.assign I already created issue for that 

I reviewed the changes in commit jjyutm4532@e9c291c and it look good.

Thanks your quick response

**Comment by alplabin** [comment]
It has been updated in [v0.1.6](https://github.com/binance/binance-futures-connector-node/releases/tag/v0.1.6)
