### ISSUE TITLE
README 的 websocket 示例错误

### ISSUE THREAD

**Issue by JxJPu9bD** [binance/binance-futures-connector-node#2]
README中关于 websocket的示例有误

![image](https://github.com/binance/binance-futures-connector-node/assets/12554248/6eae3d57-fc87-43ed-926a-008ff5a39920)

并没有直接导出对象， 正确的导入应该是 
```
const UMStream = require("@binance/futures-connector/src/modules/websocket/UMStream");

```

**Comment by Ferezoz** [comment]
This is still an issue

**Comment by alplabin** [comment]
This has been updated in [v0.1.6](https://github.com/binance/binance-futures-connector-node/releases/tag/v0.1.6)
