### ISSUE TITLE
Example code for changing Margin Type is incorrect

### ISSUE THREAD

**Issue by vuongnq10** [binance/binance-futures-connector-node#9]
### Issue subject

I'm implementing the trading bot. Looking for a function to change margin Type and got this function in the link
https://github.com/binance/binance-futures-connector-node/blob/main/examples/um_futures/account/changeMarginType.js

Here is the code

```javascript
const { UMFutures } = require('../../../src')

const apiKey = ''
const apiSecret = ''
const umFuturesClient = new UMFutures(apiKey, apiSecret, {
  baseURL: 'https://fapi.binance.com'
})

umFuturesClient
  .changeInitialLeverage('BNBUSDT', 'CROSSED')
  .then((response) => console.log(response))
  .catch(console.error)
```

### Expected behaviour

By searching the whole library, I believe that the code should be replaced function `changeInitialLeverage` by `changeMarginType`

```javascript
const { UMFutures } = require('../../../src')

const apiKey = ''
const apiSecret = ''
const umFuturesClient = new UMFutures(apiKey, apiSecret, {
  baseURL: 'https://fapi.binance.com'
})

umFuturesClient
  .changeMarginType('BNBUSDT', 'CROSSED')
  .then((response) => console.log(response))
  .catch(console.error)
```

### Actual behaviour

N/A

### Steps to reproduce

N/A

### Environment

Provide any relevant information about your setup, such as:

- Version of binance-futures-connector-node: [binance/rc-0.1.3](https://github.com/binance/binance-futures-connector-node/commit/82a129efec5fab2dd4f605a2d12a28ea98a5e257)
- Node version: N/A
- Operating system: N/A

**Comment by alplabin** [comment]
It has been fixed in the latest release: https://github.com/binance/binance-futures-connector-node/releases/tag/v0.1.4
